[package]
name = "pim-crypto"
version = "0.1.3"
edition = "2021"

[dependencies]
pim-core = { workspace = true }
x25519-dalek = { workspace = true }
ed25519-dalek = { workspace = true }
aes-gcm = { workspace = true }
hkdf = { workspace = true }
sha2 = { workspace = true }
hmac = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = "3"
