[package]
name = "pim-wifidirect"
version = "0.1.0"
edition = "2021"

[dependencies]
pim-core = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
futures-util = "0.3"

[target.'cfg(target_os = "macos")'.dependencies]
async-dnssd = "0.5.1"
