[package]
name = "pim-transport"
version = "0.1.4"
edition = "2021"
description = "Transport abstraction layer and adapters for the Proximity Internet Mesh"
license.workspace = true
repository.workspace = true

[dependencies]
libc = { workspace = true }
pim-core = { workspace = true }
pim-protocol = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
bytes = { workspace = true }
