[package]
name = "pim-transport"
version = "0.1.1"
edition = "2021"

[dependencies]
libc = { workspace = true }
pim-core = { workspace = true }
pim-protocol = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
bytes = { workspace = true }
